# Model Setting
z_dim: 100
channels: 3
nf: 64
model_name: 'dcgan'

# dataset
dataset_name: 'cifar10' # ['mnist','cifar10']

# training setting
epochs: 30
batch_size: 128
lr: 0.0002
sample_interval: 5
